


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."role" AS ENUM (
    'owner',
    'manager',
    'event_creator',
    'door_person',
    'member'
);


ALTER TYPE "public"."role" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Attendees" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event" bigint NOT NULL,
    "member" bigint NOT NULL,
    "checkedin" boolean DEFAULT false NOT NULL,
    "paid" boolean DEFAULT false
);


ALTER TABLE "public"."Attendees" OWNER TO "postgres";


ALTER TABLE "public"."Attendees" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Attendees_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Circles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "community" bigint,
    "member" bigint,
    "role" "public"."role"
);


ALTER TABLE "public"."Circles" OWNER TO "postgres";


COMMENT ON TABLE "public"."Circles" IS 'Communities and their members';



ALTER TABLE "public"."Circles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Circles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."communities" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "public" boolean DEFAULT true NOT NULL,
    "location" json,
    "description" "text",
    "languages" "text"[],
    "email" "text",
    "website" "text",
    "picture" "text",
    "established" "date",
    CONSTRAINT "communities_email_check" CHECK (("email" ~* '^[a-zA-Z0-9_+&-]+(?:.[a-zA-Z0-9_+&-]+)*@(?:[a-zA-Z0-9-]+.)+[a-zA-Z]{2,7}$'::"text")),
    CONSTRAINT "communities_website_check" CHECK (("website" ~* '^((((https?|ftps?|gopher|telnet|nntp)://)|(mailto:|news:))(%[0-9A-Fa-f]{2})+)([[:blank:|:blank:]])?$'::"text"))
);


ALTER TABLE "public"."communities" OWNER TO "postgres";


ALTER TABLE "public"."communities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Community_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "community" bigint,
    "public" boolean NOT NULL,
    "capacity" numeric,
    "price" numeric,
    "start" timestamp with time zone NOT NULL,
    "finish" timestamp with time zone,
    "location" "text",
    "description" "text",
    "title" "text",
    "est" "date",
    "picture" "text"
);


ALTER TABLE "public"."Events" OWNER TO "postgres";


ALTER TABLE "public"."Events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Members" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "email" "text",
    "avatar_url" "text",
    "uid" "uuid" NOT NULL
);


ALTER TABLE "public"."Members" OWNER TO "postgres";


ALTER TABLE "public"."Members" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Member_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Attendees"
    ADD CONSTRAINT "Attendees_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Circles"
    ADD CONSTRAINT "Circles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."communities"
    ADD CONSTRAINT "Community_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."communities"
    ADD CONSTRAINT "Community_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Members"
    ADD CONSTRAINT "Member_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Members"
    ADD CONSTRAINT "Member_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Members"
    ADD CONSTRAINT "Members_uid_key" UNIQUE ("uid");



ALTER TABLE ONLY "public"."Attendees"
    ADD CONSTRAINT "Attendees_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."Events"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Attendees"
    ADD CONSTRAINT "Attendees_member_fkey" FOREIGN KEY ("member") REFERENCES "public"."Members"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Circles"
    ADD CONSTRAINT "Circles_community_fkey" FOREIGN KEY ("community") REFERENCES "public"."communities"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Circles"
    ADD CONSTRAINT "Circles_member_fkey" FOREIGN KEY ("member") REFERENCES "public"."Members"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_community_fkey" FOREIGN KEY ("community") REFERENCES "public"."communities"("id") ON DELETE CASCADE;



CREATE POLICY "Allow owners to run loose" ON "public"."communities" USING ((EXISTS ( SELECT 1
   FROM "public"."Circles" "c"
  WHERE (("c"."community" = "communities"."id") AND ("c"."member" = ( SELECT "m"."id"
           FROM "public"."Members" "m"
          WHERE ("m"."uid" = "auth"."uid"()))) AND ("c"."role" = 'owner'::"public"."role"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."Circles" "c"
  WHERE (("c"."community" = "communities"."id") AND ("c"."member" = ( SELECT "m"."id"
           FROM "public"."Members" "m"
          WHERE ("m"."uid" = "auth"."uid"()))) AND ("c"."role" = 'owner'::"public"."role")))));



ALTER TABLE "public"."Attendees" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Circles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Create Communities" ON "public"."communities" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."communities" FOR SELECT USING (true);



ALTER TABLE "public"."Events" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Managed by owner" ON "public"."Members" USING (("uid" = "auth"."uid"())) WITH CHECK (("uid" = "auth"."uid"()));



ALTER TABLE "public"."Members" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."communities" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."Attendees" TO "anon";
GRANT ALL ON TABLE "public"."Attendees" TO "authenticated";
GRANT ALL ON TABLE "public"."Attendees" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Attendees_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Attendees_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Attendees_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Circles" TO "anon";
GRANT ALL ON TABLE "public"."Circles" TO "authenticated";
GRANT ALL ON TABLE "public"."Circles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Circles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Circles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Circles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."communities" TO "anon";
GRANT ALL ON TABLE "public"."communities" TO "authenticated";
GRANT ALL ON TABLE "public"."communities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Community_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Community_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Community_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Events" TO "anon";
GRANT ALL ON TABLE "public"."Events" TO "authenticated";
GRANT ALL ON TABLE "public"."Events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Members" TO "anon";
GRANT ALL ON TABLE "public"."Members" TO "authenticated";
GRANT ALL ON TABLE "public"."Members" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Member_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Member_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Member_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































RESET ALL;

